In [12]:
# IRIS flower Grid search

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV

In [4]:
df = pd.read_csv("C:\\Users\\Sandeep\\OneDrive\\Desktop\\Classes and Files\\Iris.csv")

In [5]:
df.shape

(150, 5)

In [6]:
df.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'iris'], dtype='object')

In [7]:
df.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
iris            0
dtype: int64

In [8]:
le = LabelEncoder()

In [9]:
X = df[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = le.fit_transform(df[['iris']])

C:\Users\Sandeep\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7)

In [11]:
print("Shapes")
print("X_train",X_train.shape)
print("y_train",y_train.shape)
print("X_test",X_test.shape)
print("y_test",y_test.shape)

Shapes
X_train (105, 4)
y_train (105,)
X_test (45, 4)
y_test (45,)


In [15]:
'''
Max_depth = 3, 4
n_estimator = 20 , 50 , 300
learning rate = 0.1 , 0.2 , 0.3

'''

'\ndadawd\n\n'

In [16]:
parameter = {
    'learning_rate' : [0.1,0.2],
    'n_estimator' : [20,50,300],
    'max_depth' : [3,4]
}

In [21]:
# Default model

from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [31]:
grid_search = GridSearchCV(estimator = xgb, param_grid = parameter, n_jobs = -1)
grid_search.fit(X_train, y_train)

C:\Users\Sandeep\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:01:53] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0cec3277c4d9d0165-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "n_estimator" } are not used.

  warnings.warn(smsg, UserWarning)


GridSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_b...
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     objective='multi:softprob', ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.2], 'max_depth': [3, 4],
                         'n_estimator': [20, 50, 300]})

In [32]:
grid_search.best_estimator_

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimator=20, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [39]:
xgb_best = XGBClassifier(max_depth = 3, n_estimator = 20, learning_rate = 0.1)
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [40]:
pred_train = xgb.predict(X_train)

print("Confusion matrix")
print(confusion_matrix(y_train, pred_train))
print(" ")
print("Classification Report")
print(classification_report(y_train, pred_train))

Confusion matrix
[[39  0  0]
 [ 0 31  0]
 [ 0  0 35]]
 
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       1.00      1.00      1.00        31
           2       1.00      1.00      1.00        35

    accuracy                           1.00       105
   macro avg       1.00      1.00      1.00       105
weighted avg       1.00      1.00      1.00       105

