In [33]:
# Finding the species of IRIS flower featuring Multiclass Classification using xgboost

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv("C:\\Users\\Sandeep\\OneDrive\\Desktop\\Classes and Files\\Iris.csv")

In [7]:
df.shape

(150, 5)

In [13]:
df.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'iris'], dtype='object')

In [25]:
df.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
iris            0
dtype: int64

In [36]:
le = LabelEncoder()

In [37]:
X = df[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = le.fit_transform(df[['iris']])

C:\Users\Sandeep\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7)

In [39]:
print("Shapes")
print("X_train",X_train.shape)
print("y_train",y_train.shape)
print("X_test",X_test.shape)
print("y_test",y_test.shape)

Shapes
X_train (105, 4)
y_train (105,)
X_test (45, 4)
y_test (45,)


In [40]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [41]:
pred_train = xgb.predict(X_train)

print("Confusion matrix")
print(confusion_matrix(pred_train, y_train))
print(" ")
print("Classification Report")
print(classification_report(pred_train, y_train))

Confusion matrix
[[30  0  0]
 [ 0 38  0]
 [ 0  0 37]]
 
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        38
           2       1.00      1.00      1.00        37

    accuracy                           1.00       105
   macro avg       1.00      1.00      1.00       105
weighted avg       1.00      1.00      1.00       105



In [42]:
xgb.fit(X_test, y_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [43]:
pred_test = xgb.predict(X_test)

print("Confusion matrix")
print(confusion_matrix(pred_test, y_test))
print(" ")
print("Classification Report")
print(classification_report(pred_test, y_test))

Confusion matrix
[[20  0  0]
 [ 0 12  0]
 [ 0  0 13]]
 
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

